config/routes.rb
MyWords::Application.routes.draw do
  root to: 'home#index'
  match '/auth/evernote', to: 'auth#evernote', as: :evernote_oauth_callback, via: :get
  match '/logout', to: 'auth#reset', as: :logout, via: :get
  resources :notebooks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def evernote
    request_token = session[:request_token]
    access_token = request_token.get_access_token(oauth_verifier: params[:oauth_verifier])
    session[:access_token] = access_token.token
    redirect_to root_path
  end

  def reset
    reset_session
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  def index
    client = EvernoteOAuth::Client.new(token: session[:access_token])
    note_store = client.note_store
    @notebooks = note_store.listNotebooks(session[:access_token])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  EvernoteClient = EvernoteOAuth::Client.new(YAML.load(File.read('config/evernote.yml'))[Rails.env])
  def evernote_oauth_url
    session[:request_token] = EvernoteClient.request_token(oauth_callback: evernote_oauth_callback_url)
    session[:request_token].authorize_url
  end
end

app/views/home/index.html.slim
- if session[:access_token]
  = link_to 'Logout Evernote', logout_path
  br
  = "Evernote Access Token: #{session[:access_token]}"
  = link_to 'List Notebooks', notebooks_path
- else
  = link_to 'Login Evernote', evernote_oauth_url

app/views/layouts/application.html.slim
doctype html
html
  head
    title Title
    = stylesheet_link_tag 'application', media: 'all', data: {turbolinks_track: true }
    = javascript_include_tag 'application', data: {turbolinks_track: true }
    = csrf_meta_tags
  body
    == yield

app/views/notebooks/index.html.slim
|Notebooks:
br

- @notebooks.each do |notebook|
  = notebook.name
  br